services:
    timetm.calendar.month:
        class: TimeTM\CalendarBundle\Model\CalendarMonth
        arguments: [ "@router" , "@translator" ]

    timetm.calendar.day:
        class: TimeTM\CalendarBundle\Model\CalendarDay
        arguments: [ "@router" , "@translator" ]

    timetm.calendar.week:
        class: TimeTM\CalendarBundle\Model\CalendarWeek
        arguments: [ "@router" , "@translator" ]

    timetm.calendar.times:
        class: TimeTM\CalendarBundle\Model\Times
        arguments: [ "%timetm.dayStart%" , "%timetm.dayEnd%" ]
    timetm.calendar.helper:
        class: TimeTM\CalendarBundle\Helper\CalendarHelper
        arguments: ["@doctrine.orm.entity_manager"]
