services:
    timetm.profile.form.type:
            class: TimeTM\UserBundle\Form\Type\ProfileFormType
            arguments: [%fos_user.model.user.class%]
            tags:
                - { name: form.type, alias: timetm_user_profile }
