services:
    timetm_user.registration_completed_listener:
        class: TimeTM\UserBundle\EventListener\RegistrationCompletedListener
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: kernel.event_subscriber }
    timetm_user.registration_success_listener:
        class: TimeTM\UserBundle\EventListener\RegistrationSuccessListener
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: kernel.event_subscriber }