<?php

/**
 * This file is part of the TimeTM package.
 *
 * (c) TimeTM <https://github.com/timetm>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace TimeTM\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

    /**
     * get user's default agenda
     *
     * @param $user
     *
     * @return int agenda id
     *
     */
    public function findDefaultAgenda($user) {

        $agendas = $this
            ->getEntityManager()
            ->getRepository('TimeTMCoreBundle:Agenda');

        $default = $agendas->findOneBy(array('user' => $user, 'default' => 1));

        return $default->getId();
    }
}
