services:
#
# -- Gobal services -----------------------------------------------------------
#
    timetm.global:
        class: TimeTM\CoreBundle\Helper\GlobalHelper
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", "@service_container", "@twig", "@session"]

#
# -- Calendar services --------------------------------------------------------
#
    timetm.calendar.month:
        class: TimeTM\CoreBundle\Model\CalendarMonth
        arguments: [ "@router" , "@translator", "@timetm.calendar.helper" ]

    timetm.calendar.day:
        class: TimeTM\CoreBundle\Model\CalendarDay
        arguments: [ "@router" , "@translator", "@timetm.calendar.helper" ]

    timetm.calendar.week:
        class: TimeTM\CoreBundle\Model\CalendarWeek
        arguments: [ "@router" , "@translator" ]

    timetm.calendar.times:
        class: TimeTM\CoreBundle\Model\Times
        arguments: [ "%timetm.dayStart%" , "%timetm.dayEnd%" ]

    timetm.calendar.helper:
        class: TimeTM\CoreBundle\Helper\CalendarHelper
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", "@timetm.event.helper"]

#
# -- Contact services ---------------------------------------------------------
#
    timetm.contact.helper:
        class: TimeTM\CoreBundle\Helper\ContactHelper
        arguments: ["@doctrine.orm.entity_manager"]

#
# -- Event services -----------------------------------------------------------
#
    timetm.event.helper:
        class: TimeTM\CoreBundle\Helper\EventHelper
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", "@session"]

#
# -- Agenda services ----------------------------------------------------------
#
    timetm.agenda.helper:
        class: TimeTM\CoreBundle\Helper\AgendaHelper
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]

#
# -- User services ------------------------------------------------------------
#
    timetm_user.registration_completed_listener:
        class: TimeTM\CoreBundle\EventListener\RegistrationCompletedListener
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: kernel.event_subscriber }
