services:
#
# -- Calendar services --------------------------------------------------------
#
    timetm.calendar.month:
        class: TimeTM\CoreBundle\Model\CalendarMonth
        arguments: [ "@router" , "@translator" ]

    timetm.calendar.day:
        class: TimeTM\CoreBundle\Model\CalendarDay
        arguments: [ "@router" , "@translator" ]

    timetm.calendar.week:
        class: TimeTM\CoreBundle\Model\CalendarWeek
        arguments: [ "@router" , "@translator" ]

    timetm.calendar.times:
        class: TimeTM\CoreBundle\Model\Times
        arguments: [ "%timetm.dayStart%" , "%timetm.dayEnd%" ]

    timetm.calendar.helper:
        class: TimeTM\CoreBundle\Helper\CalendarHelper
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", "@timetm.event.helper"]
#
# -- Contact services ---------------------------------------------------------
#
    timetm.contact.helper:
        class: TimeTM\CoreBundle\Helper\ContactHelper
#
# -- Event services -----------------------------------------------------------
#
    timetm.event.helper:
        class: TimeTM\CoreBundle\Helper\EventHelper
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]
#
# -- User services ------------------------------------------------------------
#
    timetm_user.registration_completed_listener:
        class: TimeTM\CoreBundle\EventListener\RegistrationCompletedListener
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: kernel.event_subscriber }
