<?php

namespace TimeTM\CoreBundle\Entity;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository {

    public function findAllActive() {

        return $this->createQueryBuilder('t')
            ->andWhere('t.donedate is NULL')
            ->getQuery()
            ->getResult();
    }
}
